### ISSUE TITLE
phet.dot.Range is not a constructor

### ISSUE THREAD

**Issue by phet-steele** [phetsims/energy-skate-park-basics#378]
```
phet-io : test-iframe-api
753 out of 754 tests passed. 1 failed.
: iframe api tests for energy-skate-park-basics failed:
No error should occur in setting state: Error: phet.dot.Range is not a constructor
    at Object.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1504882953652/phet-io/tests/test-iframe-api/test-iframe-api.js:142:20)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1504882953652/phet-io-wrappers/common/js/SimIFrameClient.js:155:41)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1504882953652/phet-io-wrappers/common/js/SimIFrameClient.js:198:13)
```

**Comment by samreid** [comment]
Oddly, the state wrapper was trying to restore range without ever having imported DOT/Range.  I searched for the reason Range was trying to be deserialized but could not find it.  I added Range to energy skate park: basics but this will happen again someday.
