### ISSUE TITLE
CT event indexing failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#442]
```
energy-skate-park-basics : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park-basics: event indexing failed:
Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.
    at testInputEventIndexing (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/phet-io-wrappers/js/tests/SimTests.js?bust=1542220566379:395:11)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/phet-io-wrappers/js/tests/SimTests.js?bust=1542220566379:467:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sherpa/lib/require-2.1.11.js:866:35)
    at Module.enable (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sherpa/lib/require-2.1.11.js:1143:14)
    at Module.init (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (https://bayes.colorado.edu/continuous-testing/snapshot-1542218899812/sherpa/lib/require-2.1.11.js:1170:55)


id: Bayes Chrome
Approximately 11/14/2018, 11:08:19 AM
```

**Comment by KatieWoe** [comment]
```
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/assert/js/assert.js:22:13)
    at EnergySkateParkBasicsModel.interactWithTracksWhileFalling (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542283815006:668:21)
    at EnergySkateParkBasicsModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542283815006:526:23)
    at EnergySkateParkBasicsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542283815006:1295:69)
    at EnergySkateParkBasicsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542283815006:402:31)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542283815006:205:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/axon/js/Emitter.js?bust=1542283815006:194:53)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542283815006:907:34)
    at EnergySkateParkBasicsSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542283815006:888:14)
    at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542283815006:871:14)
id: Bayes Chrome
Approximately 11/15/2018, 3:55:09 AM
energy-skate-park-basics : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: energy-skate-park-basics: event indexing failed:
Expected at least one assertion, but none were run - call expect(0) to accept zero assertions.
    at testInputEventIndexing (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/phet-io-wrappers/js/tests/SimTests.js?bust=1542289800206:395:11)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/phet-io-wrappers/js/tests/SimTests.js?bust=1542289800206:467:5
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/sherpa/lib/require-2.1.11.js:866:35)
    at Module.enable (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/sherpa/lib/require-2.1.11.js:1143:14)
    at Module.init (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/sherpa/lib/require-2.1.11.js:774:16)
    at callGetModule (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/sherpa/lib/require-2.1.11.js:1170:55)


id: Bayes Chrome
Approximately 11/15/2018, 3:55:09 AM
energy-skate-park-basics : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 11/15/2018, 3:55:09 AM
energy-skate-park-basics : xss-fuzz : run
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/assert/js/assert.js:22:13)
    at EnergySkateParkBasicsModel.interactWithTracksWhileFalling (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542290676254:668:21)
    at EnergySkateParkBasicsModel.stepFreeFall (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542290676254:526:23)
    at EnergySkateParkBasicsModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542290676254:1295:69)
    at EnergySkateParkBasicsModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/energy-skate-park-basics/js/energy-skate-park-basics/model/EnergySkateParkBasicsModel.js?bust=1542290676254:402:31)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542290676254:205:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/axon/js/Emitter.js?bust=1542290676254:194:53)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542290676254:907:34)
    at EnergySkateParkBasicsSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542290676254:888:14)
    at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1542279309960/joist/js/Sim.js?bust=1542290676254:871:14)
id: Bayes Chrome
Approximately 11/15/2018, 3:55:09 AM
```

**Comment by samreid** [comment]
On hold until https://github.com/phetsims/energy-skate-park/issues/6 is complete

**Comment by samreid** [comment]
Event indexing seems better, but I'm still seeing the `interactWithTracksWhileFalling`, I'll create a new issue for that, closing.
