### ISSUE TITLE
CT: Memory Limits

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#455]
```
energy-skate-park-basics : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNode.track_17.controlPointNode1.inputListener.dragEndedEmitter.emitted
Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNode.track_17.controlPointNode1.inputListener.dragEndedEmitter.emitted
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at Object.start (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io/js/dataStream.js?bust=1549356869940:148:19)
    at Emitter.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/tandem/js/PhetioObject.js?bust=1549356869940:265:50)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549356869940:218:14)
    at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549356869940:328:29)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549356869940:271:16)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549356869940:1799:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549356869940:1755:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549356869940:1516:12)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549356869940:256:16)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
energy-skate-park-basics : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNode.track_45.trackDragHandler.inputListener.dragEndedEmitter.emitted
Error: Assertion failed: Only instrumented instances can emit to the data stream. Has it been disposed? energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNode.track_45.trackDragHandler.inputListener.dragEndedEmitter.emitted
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at Object.start (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/phet-io/js/dataStream.js?bust=1549365009509:148:19)
    at Emitter.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/tandem/js/PhetioObject.js?bust=1549365009509:265:50)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549365009509:218:14)
    at TrackDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549365009509:328:29)
    at Object.up (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/SimpleDragHandler.js?bust=1549365009509:271:16)
    at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549365009509:1799:27)
    at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549365009509:1755:12)
    at Input.upEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549365009509:1516:12)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/scenery/js/input/Input.js?bust=1549365009509:256:16)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
energy-skate-park-basics : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 2/5/2019, 12:29:16 AM
energy-skate-park-basics : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 2/5/2019, 12:29:16 AM
energy-skate-park-basics : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed
Error: Assertion failed
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/assert/js/assert.js:22:13)
    at SkaterState.updateThermalEnergy (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/energy-skate-park/js/energy-skate-park/common/model/SkaterState.js?bust=1549361464031:236:17)
    at PlaygroundModel.stepGround (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1549361464031:467:22)
    at PlaygroundModel.stepModel (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1549361464031:1300:70)
    at PlaygroundModel.step (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/energy-skate-park/js/energy-skate-park/common/model/EnergySkateParkModel.js?bust=1549361464031:401:31)
    at before (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/joist/js/Sim.js?bust=1549361464031:217:24)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/axon/js/Emitter.js?bust=1549361464031:201:34)
    at EnergySkateParkBasicsSim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/joist/js/Sim.js?bust=1549361464031:922:34)
    at EnergySkateParkBasicsSim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/joist/js/Sim.js?bust=1549361464031:903:14)
    at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1549351756432/joist/js/Sim.js?bust=1549361464031:886:14)
id: Bayes Chrome
Approximately 2/5/2019, 12:29:16 AM
```

**Comment by samreid** [comment]
I don't recall seeing this lately, closing.
