### ISSUE TITLE
CT t.link is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#459]
```
energy-skate-park-basics : fuzz : built : load
Query: fuzz&memoryLimit=1000
Uncaught TypeError: t.link is not a function
TypeError: t.link is not a function
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1261936)
    at e [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1265378)
    at e.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1272130)
    at e.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1273398)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1494052)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1549742)
    at e.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1605964)
    at e.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:808652)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1049345)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1049422
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : fuzz : built : run
Query: fuzz&memoryLimit=1000
Uncaught TypeError: t.link is not a function
TypeError: t.link is not a function
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1261936)
    at e [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1265378)
    at e.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1272130)
    at e.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1273398)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1494052)
    at new e (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1549742)
    at e.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1605964)
    at e.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:808652)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1049345)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/energy-skate-park-basics/build/phet/energy-skate-park-basics_en_phet.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000:1075:1049422
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : fuzz : built-phet-io : load
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: e.link is not a function
TypeError: e.link is not a function
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1304025)
    at t [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1307467)
    at t.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1314219)
    at t.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1315487)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1536141)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1591831)
    at t.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1648053)
    at t.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:850959)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1091434)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1091511
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : fuzz : built-phet-io : run
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: e.link is not a function
TypeError: e.link is not a function
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1304025)
    at t [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1307467)
    at t.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1314219)
    at t.i (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1315487)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1536141)
    at new t (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1591831)
    at t.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1648053)
    at t.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:850959)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1091434)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564-phet-io/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1073:1091511
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at Text.setText (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:126:17)
    at Text.set text [as text] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:146:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4986:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:67:656)
    at Text.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4973:9)
    at Text.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:526:12)
    at new Text (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:90:10)
    at new NumberControl (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/NumberControl.js?:217:23)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at Text.setText (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:126:17)
    at Text.set text [as text] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:146:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4986:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:67:656)
    at Text.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4973:9)
    at Text.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:526:12)
    at new Text (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:90:10)
    at new NumberControl (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/NumberControl.js?:217:23)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at Text.setText (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:126:17)
    at Text.set text [as text] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:146:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4986:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:67:656)
    at Text.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4973:9)
    at Text.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:526:12)
    at new Text (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:90:10)
    at new NumberControl (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/NumberControl.js?:217:23)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at Text.setText (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:126:17)
    at Text.set text [as text] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:146:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4986:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:67:656)
    at Text.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4973:9)
    at Text.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:526:12)
    at new Text (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:90:10)
    at new NumberControl (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/NumberControl.js?:217:23)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : phet-io-tests : assert
7 out of 9 tests passed. 2 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: text should be a string or number
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: energy-skate-park-basics: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: text should be a string or number
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : phet-io-tests : no-assert
7 out of 9 tests passed. 2 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: text should be a string or number
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: energy-skate-park-basics: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: text should be a string or number
https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at Text.setText (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:126:17)
    at Text.set text [as text] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:146:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4986:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:67:656)
    at Text.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4973:9)
    at Text.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:526:12)
    at new Text (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:90:10)
    at new NumberControl (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/NumberControl.js?:217:23)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
energy-skate-park-basics : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: text should be a string or number
Error: Assertion failed: text should be a string or number
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/assert/js/assert.js:22:13)
    at Text.setText (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:126:17)
    at Text.set text [as text] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:146:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4986:25
    at u (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:5:432)
    at Function.ru (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/sherpa/lib/lodash-4.17.4.min.js?:67:656)
    at Text.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:4973:9)
    at Text.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Node.js?:526:12)
    at new Text (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery/js/nodes/Text.js?:90:10)
    at new NumberControl (https://bayes.colorado.edu/continuous-testing/snapshot-1565084852564/scenery-phet/js/NumberControl.js?:217:23)
id: Bayes Chrome
Approximately 8/6/2019, 3:47:32 AM
```

**Comment by samreid** [comment]
Co-assigning @jessegreenberg in case he has been in the area.

**Comment by jessegreenberg** [comment]
Definitely have, sorry about that. Fix comming shortly.

**Comment by jessegreenberg** [comment]
Fixed above, ESP:B is fuzzing without error locally so I assume this is fixed.
