### ISSUE TITLE
CT Failure to grunt snapshot

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#460]
```
energy-skate-park-basics : build : phet
Failure to grunt snapshot-1568193194627/energy-skate-park-basics:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (energy-skate-park-basics, brands: phet)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1568193194627/energy-skate-park/js/energy-skate-park/EnergySkateParkSim.js'
In module tree:
    energy-skate-park-basics-main
      ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim

  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/js/grunt/requireBuild.js:111:15
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1568193194627/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : build : phet-io
Failure to grunt snapshot-1568193194627-phet-io/energy-skate-park-basics:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (energy-skate-park-basics, brands: phet, phet-io)
Building brand: phet
Fatal error: Perennial task failed:
Error: Error: Error: ENOENT: no such file or directory, open '/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/energy-skate-park/js/energy-skate-park/EnergySkateParkSim.js'
In module tree:
    energy-skate-park-basics-main
      ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim

  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/js/grunt/requireBuild.js:111:15
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:3059:39
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:2999:25
  at Function.prim.nextTick (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:28083:9)
  at Object.errback (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:2998:26)
  at Object.callback (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:2984:23)
  at Object.then (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:3038:23)
  at runBuild (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:30302:48)
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1389:34)
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1439:21
  at each (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:309:31)
  at Module.emit (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1438:17)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1188:30)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at Module.<anonymous> (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1264:30)
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:384:23
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:2697:17
  at Object.execCb (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1946:33)
  at Module.check (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1133:51)
  at Module.enable (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1426:22)
  at Module.init (/data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1038:26)
  at /data/share/phet/continuous-testing/snapshot-1568193194627-phet-io/chipper/node_modules/requirejs/bin/r.js:1710:36
  at _combinedTickCallback (internal/process/next_tick.js:132:7)
  at process._tickCallback (internal/process/next_tick.js:181:9)

Full Error details:
{}


Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : phet-io-tests : assert
6 out of 9 tests passed. 3 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: energy-skate-park-basics: test launchSimulation failed:
failed, expected argument to be truthy, was: false
    at https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/js/tests/SimTests.js?:409:16
    at errorListenerFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/common/js/Client.js:758:11)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/common/js/Client.js:344:65
    at Array.forEach (<anonymous>)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/common/js/Client.js:344:44)

SimTests: energy-skate-park-basics: event indexing failed:
Uncaught Error: Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : phet-io-tests : no-assert
6 out of 9 tests passed. 3 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/js/tests/SimTests.js?:341

SimTests: energy-skate-park-basics: test launchSimulation failed:
failed, expected argument to be truthy, was: false
    at https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/js/tests/SimTests.js?:409:16
    at errorListenerFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/common/js/Client.js:758:11)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/common/js/Client.js:344:65
    at Array.forEach (<anonymous>)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/common/js/Client.js:344:44)

SimTests: energy-skate-park-basics: event indexing failed:
Uncaught Error: Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/phet-io-wrappers/js/tests/SimTests.js?:531


id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
energy-skate-park-basics : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
Error: Script error for "ENERGY_SKATE_PARK/energy-skate-park/EnergySkateParkSim", needed by: ENERGY_SKATE_PARK_BASICS/energy-skate-park-basics/EnergySkateParkBasicsSim
https://requirejs.org/docs/errors.html#scripterror
    at makeError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:168:17)
    at HTMLScriptElement.onScriptError (https://bayes.colorado.edu/continuous-testing/snapshot-1568193194627/sherpa/lib/require-2.3.6.js:1738:36)
id: Bayes Chrome
Approximately 9/11/2019, 3:13:14 AM
```

**Comment by jessegreenberg** [comment]
I deleted EnergySkateParkSim because I couldn't find usages of it, this is definitely related to that.

**Comment by jessegreenberg** [comment]
My apologies, it is definitely used in energy-skate-park-basics. Not sure why I didn't see it before, maybe I was excluding basics in my search or something.

**Comment by jessegreenberg** [comment]
Oh correction, it was moved to common. I miss-remembered.

**Comment by jessegreenberg** [comment]
Fixed.
