### ISSUE TITLE
CT Any static registered PhetioObject can never be deregistered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#469]
```
energy-skate-park-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.introScreen.model.doubleWellTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.introScreen.model.doubleWellTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583747981048:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onPhetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/phetioAPIValidation.js:160:12)
    at PhetioEngine.phetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioEngine.js:492:25)
    at Object.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioEngine.js:537:52)
    at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/Tandem.js:168:38)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:557:19)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/axon/js/Property.js:451:11)
    at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:199:20)
    at Track.disposeTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/energy-skate-park/js/energy-skate-park/common/model/Track.js:191:29)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
energy-skate-park-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583747981048:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioCommandProcessor.js:107:18
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
energy-skate-park-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.introScreen.model.doubleWellTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
Error: Assertion failed: PhET-iO API error:
energySkateParkBasics.introScreen.model.doubleWellTrack.physicalProperty:  6. Any static, registered PhetioObject can never be deregistered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583765019981:22:13)
    at PhetioAPIValidation.assertAPIError (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/phetioAPIValidation.js:277:15)
    at PhetioAPIValidation.onPhetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/phetioAPIValidation.js:160:12)
    at PhetioEngine.phetioObjectRemoved (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioEngine.js:492:25)
    at Object.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioEngine.js:537:52)
    at Tandem.removePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/Tandem.js:168:38)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:557:19)
    at BooleanProperty.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/axon/js/Property.js:451:11)
    at BooleanProperty.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:199:20)
    at Track.disposeTrack (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/energy-skate-park/js/energy-skate-park/common/model/Track.js:191:29)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
energy-skate-park-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583765019981:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioCommandProcessor.js:107:18
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
energy-skate-park-basics : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 3/9/2020, 3:16:42 AM
energy-skate-park-basics : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 3/9/2020, 3:16:42 AM
```

**Comment by pixelzoom** [comment]
Also occurring in energy-skate-park.

**Comment by samreid** [comment]
We will soon be instrumenting this sim for PhET-iO.  We will likely be able to address this issue then.

**Comment by KatieWoe** [comment]
Not seeing this in CT right now. Closing
