### ISSUE TITLE
CT: createTandem is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#470]
```
energy-skate-park-basics : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (energy-skate-park-basics, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 4696ms
>> Unused string: key=properties.speed, value=Speed
>> Unused string: key=small, value=Small
>> Unused string: key=controls.mass, value=Mass
>> Unused string: key=slow.motion, value=Slow Motion
>> Unused string: key=energy.thermal, value=Thermal
>> Unused string: key=energy.total, value=Total
>> Unused string: key=plots.bar-graph, value=Bar Graph
>> Unused string: key=pieChart, value=Pie Chart
>> Unused string: key=controls.show-grid, value=Grid
>> Unused string: key=large, value=Large
>> Unused string: key=controls.gravity.lots, value=Lots
>> Unused string: key=energy.kinetic, value=Kinetic
>> Unused string: key=energy.potential, value=Potential
>> Unused string: key=normal, value=Normal
>> Unused string: key=controls.gravity.none, value=None
>> Unused string: key=energy.energy, value=Energy
>> Unused string: key=controls.friction.title, value=Friction
>> Unused string: key=controls.restart-skater, value=Restart Skater
>> Unused string: key=zeroMeters, value=0 meters
>> Production minification complete: 35996ms (2196777 bytes)
>> Debug minification complete: 1ms (6466478 bytes)
Building brand: phet-io
>> Webpack build complete: 3629ms
>> Unused string: key=properties.speed, value=Speed
>> Unused string: key=small, value=Small
>> Unused string: key=controls.mass, value=Mass
>> Unused string: key=slow.motion, value=Slow Motion
>> Unused string: key=energy.thermal, value=Thermal
>> Unused string: key=energy.total, value=Total
>> Unused string: key=plots.bar-graph, value=Bar Graph
>> Unused string: key=pieChart, value=Pie Chart
>> Unused string: key=controls.show-grid, value=Grid
>> Unused string: key=large, value=Large
>> Unused string: key=controls.gravity.lots, value=Lots
>> Unused string: key=energy.kinetic, value=Kinetic
>> Unused string: key=energy.potential, value=Potential
>> Unused string: key=normal, value=Normal
>> Unused string: key=controls.gravity.none, value=None
>> Unused string: key=energy.energy, value=Energy
>> Unused string: key=controls.friction.title, value=Friction
>> Unused string: key=controls.restart-skater, value=Restart Skater
>> Unused string: key=zeroMeters, value=0 meters
>> Production minification complete: 31843ms (2213591 bytes)
>> Debug minification complete: 31660ms (2477186 bytes)
>> No client guides found at ../phet-io-client-guides/energy-skate-park-basics/, no guides being built.
Fatal error: Perennial task failed: Error: TypeError: i.createTandem is not a function
at bT (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1391181)
at new i (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1391000)
at i.<anonymous> (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:2728)
at new i (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1394411)
at new i (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1395137)
at new i (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1682350)
at new i (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1701071)
at i.<anonymous> (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:2728)
at new i (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:1709313)
at i.<anonymous> (http://localhost:40716/energy-skate-park-basics/build/phet-io/energy-skate-park-basics_all_phet-io.html?ea&brand=phet-io&phetioStandalone&phetioPrintAPI:86:2728)
Snapshot from 7/20/2020, 2:43:02 PM

----------------------------------

energy-skate-park-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595277782900%22%2C%22timestamp%22%3A1595279627835%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught TypeError: tandem.createTandem is not a function
TypeError: tandem.createTandem is not a function
at createTickEntry (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:69:22)
at new PhysicalSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:49:7)
at new MassSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/MassSlider.js:27:5)
at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkMassControls.js:67:20)
at new EnergySkateParkControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkControlPanel.js:87:22)
at new EnergySkateParkScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkScreenView.js:176:25)
at new EnergySkateParkSaveSampleScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkSaveSampleScreenView.js:20:5)
at new EnergySkateParkTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkTrackSetScreenView.js:23:5)
at new EnergySkateParkBasicsTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/common/view/EnergySkateParkBasicsTrackSetScreenView.js:47:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/intro/view/IntroScreenView.js:19:5)
id: Bayes Chrome
Snapshot from 7/20/2020, 2:43:02 PM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1595277782900%22%2C%22timestamp%22%3A1595278522277%7D
Uncaught Error: Uncaught TypeError: tandem.createTandem is not a function
TypeError: tandem.createTandem is not a function
at createTickEntry (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:69:22)
at new PhysicalSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:49:7)
at new MassSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/MassSlider.js:27:5)
at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkMassControls.js:67:20)
at new EnergySkateParkControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkControlPanel.js:87:22)
at new EnergySkateParkScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkScreenView.js:176:25)
at new EnergySkateParkSaveSampleScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkSaveSampleScreenView.js:20:5)
at new EnergySkateParkTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkTrackSetScreenView.js:23:5)
at new EnergySkateParkBasicsTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/common/view/EnergySkateParkBasicsTrackSetScreenView.js:47:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/intro/view/IntroScreenView.js:19:5)
id: Bayes Chrome
Snapshot from 7/20/2020, 2:43:02 PM

----------------------------------

energy-skate-park-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park-basics&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught TypeError: tandem.createTandem is not a function
TypeError: tandem.createTandem is not a function
at createTickEntry (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:69:22)
at new PhysicalSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:49:7)
at new MassSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/MassSlider.js:27:5)
at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkMassControls.js:67:20)
at new EnergySkateParkControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkControlPanel.js:87:22)
at new EnergySkateParkScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkScreenView.js:176:25)
at new EnergySkateParkSaveSampleScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkSaveSampleScreenView.js:20:5)
at new EnergySkateParkTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkTrackSetScreenView.js:23:5)
at new EnergySkateParkBasicsTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/common/view/EnergySkateParkBasicsTrackSetScreenView.js:47:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/intro/view/IntroScreenView.js:19:5)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 7/20/2020, 2:43:02 PM

----------------------------------

energy-skate-park-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park-basics
3 out of 4 tests passed. 1 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught TypeError: tandem.createTandem is not a function
TypeError: tandem.createTandem is not a function
at createTickEntry (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:69:22)
at new PhysicalSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:49:7)
at new MassSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/MassSlider.js:27:5)
at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkMassControls.js:67:20)
at new EnergySkateParkControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkControlPanel.js:87:22)
at new EnergySkateParkScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkScreenView.js:176:25)
at new EnergySkateParkSaveSampleScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkSaveSampleScreenView.js:20:5)
at new EnergySkateParkTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkTrackSetScreenView.js:23:5)
at new EnergySkateParkBasicsTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/common/view/EnergySkateParkBasicsTrackSetScreenView.js:47:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/intro/view/IntroScreenView.js:19:5)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 7/20/2020, 2:43:02 PM

----------------------------------

energy-skate-park-basics : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1595277782900%22%2C%22timestamp%22%3A1595280982350%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: tandem.createTandem is not a function
TypeError: tandem.createTandem is not a function
at createTickEntry (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:69:22)
at new PhysicalSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/PhysicalSlider.js:49:7)
at new MassSlider (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/MassSlider.js:27:5)
at new EnergySkateParkMassControls (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkMassControls.js:67:20)
at new EnergySkateParkControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkControlPanel.js:87:22)
at new EnergySkateParkScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkScreenView.js:176:25)
at new EnergySkateParkSaveSampleScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkSaveSampleScreenView.js:20:5)
at new EnergySkateParkTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park/js/common/view/EnergySkateParkTrackSetScreenView.js:23:5)
at new EnergySkateParkBasicsTrackSetScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/common/view/EnergySkateParkBasicsTrackSetScreenView.js:47:5)
at new IntroScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595277782900/energy-skate-park-basics/js/intro/view/IntroScreenView.js:19:5)
id: Bayes Chrome
Snapshot from 7/20/2020, 2:43:02 PM
```

**Comment by samreid** [comment]
Most of these errors stem from `createTandem is not a function`.  It looks like refactoring in https://github.com/phetsims/energy-skate-park/issues/280 changed the signature of PhysicalSlider, but MassSlider was not changed.  @jessegreenberg can you please take a look?

**Comment by jessegreenberg** [comment]
Thanks, and sorry about that. MassSlider was changed but was done so incorrectly and I failed to pass the Tandem through to `super`. Fixed in the above commit.
