### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#471]
```
energy-skate-park-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596180705917%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596188401109%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596200967932%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596175175895%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596190209918%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596202039759%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596177402859%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596190693759%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596173978368%22%2C%22timestamp%22%3A1596201341879%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park-basics&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM

----------------------------------

energy-skate-park-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/phet-io-wrappers/phet-io-wrappers-tests.html?sim=energy-skate-park-basics
3 out of 4 tests passed. 1 failed.
SimTests: energy-skate-park-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/assert/js/assert.js:22:13)
at Track.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:237:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/tandem/js/PhetioObject.js:189:10)
at new Track (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/Track.js:75:5)
at Object.createTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/PremadeTracks.js:336:12)
at Function.createPremadeTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/model/EnergySkateParkTrackSetModel.js:205:26)
at createIconTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:75:46)
at createNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:110:21)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/energy-skate-park/js/common/view/SceneSelectionRadioButtonGroup.js:131:27
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596173978368/sherpa/lib/lodash-4.17.4.js:4920:15

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 7/30/2020, 11:39:38 PM
```

**Comment by jessegreenberg** [comment]
Most likely on me, assigning to myself.

**Comment by jessegreenberg** [comment]
Fixed in the above commit.
