### ISSUE TITLE
CT item not found in array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#472]
Link to https://github.com/phetsims/axon/issues/332
```
energy-skate-park-basics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607351199673%22%2C%22timestamp%22%3A1607354512056%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/createObservableArray.js:345:33)
at PlaygroundModel.joinTrackToTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1730:17)
at PlaygroundModel.joinTracks (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1531:10)
at TrackDragHandler.trackDragEnded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:226:13)
at TrackDragHandler.handleDragEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:74:10)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:31:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/scenery/js/input/SimpleDragHandler.js:237:24
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/7/2020, 7:26:39 AM

----------------------------------

energy-skate-park-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607351199673%22%2C%22timestamp%22%3A1607353736907%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/createObservableArray.js:345:33)
at PlaygroundModel.joinTrackToTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1730:17)
at PlaygroundModel.joinTracks (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1531:10)
at TrackDragHandler.trackDragEnded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:226:13)
at TrackDragHandler.handleDragEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:74:10)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:31:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/scenery/js/input/SimpleDragHandler.js:237:24
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/7/2020, 7:26:39 AM

----------------------------------

energy-skate-park-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/phet-io-wrappers/mirror-inputs/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1607351199673%22%2C%22timestamp%22%3A1607354325643%7D
Uncaught Error: Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/createObservableArray.js:345:33)
at PlaygroundModel.joinTrackToTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1730:17)
at PlaygroundModel.joinTracks (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1531:10)
at TrackDragHandler.trackDragEnded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:226:13)
at TrackDragHandler.handleDragEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:74:10)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:31:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/scenery/js/input/SimpleDragHandler.js:237:24
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/7/2020, 7:26:39 AM

----------------------------------

energy-skate-park-basics : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park-basics/energy-skate-park-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1607351199673%22%2C%22timestamp%22%3A1607356276931%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/createObservableArray.js:345:33)
at PlaygroundModel.joinTrackToTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1730:17)
at PlaygroundModel.joinTracks (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/model/EnergySkateParkModel.js:1531:10)
at TrackDragHandler.trackDragEnded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:226:13)
at TrackDragHandler.handleDragEnd (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:74:10)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/energy-skate-park/js/common/view/TrackDragHandler.js:31:26)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/scenery/js/input/SimpleDragHandler.js:237:24
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1607351199673/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 12/7/2020, 7:26:39 AM
```

**Comment by samreid** [comment]
Is this report about energy-forms-and-changes or energy-skate-park-basics?

**Comment by KatieWoe** [comment]
Basics, sorry I coppied from the wrong cell. I'll edit the issue now.

**Comment by samreid** [comment]
It appears this was addressed in https://github.com/phetsims/energy-skate-park/issues/314.  I can't reproduce the problem locally and CT is not showing problems for ESPB at the moment.
