### ISSUE TITLE
CT assertion failed PhetioObject not found for

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/energy-skate-park-basics#474]
```
energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611505289578%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611514872656%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611523071908%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611537272848%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611554030511%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611569413101%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM

----------------------------------

energy-skate-park-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/studio/?sim=energy-skate-park-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22energy-skate-park-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1611503573321%22%2C%22timestamp%22%3A1611588555300%7D
Uncaught Error: Uncaught Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
Error: Assertion failed: PhetioObject not found for energySkateParkBasics.playgroundScreen.view.graphsScreenView.trackNodeGroup.archetype.trackDragHandler.inputListener.isDraggingProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/assert/js/assert.js:25:13)
at PhetioEngine.assertPhetioObjectFound (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:345:17)
at PhetioEngine.getPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/phet-io/js/phetioEngine.js:449:20)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/tandem/js/phetioAPIValidation.js:283:96
at callback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/Timer.js:32:11)
at Timer.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/axon/js/TinyEmitter.js:85:42)
at EnergySkateParkBasicsSim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1611503573321/joist/js/Sim.js:1023:25)
id: Bayes Chrome
Snapshot from 1/24/2021, 8:52:53 AM
```

**Comment by jessegreenberg** [comment]
It looks like Tandems are getting passed through to the drag handler and isDraggingProperty. I'm not sure but I think this could be related to https://github.com/phetsims/energy-skate-park/issues/123. @samreid made commits there recently, would you mind taking a look?

**Comment by samreid** [comment]
Let's track this in https://github.com/phetsims/energy-skate-park/issues/318, closing as duplicate.
